baseurl = "https://keeks-it-blog.de/"


title = "Keeks IT-Blog"
theme = "ananke"
languageCode = "de-de"
since = 2026

enableEmoji = true  # war mal enableTwoEmojy (o.ä) - veraltet!

colorScheme = "auto"
hidecolorschemetoggle = false


[pagination]
  pagerSize = 20

[services]
[services.disqus]
  shortname = "Seb"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
style = "github-dark"

[params]
 author = "Sebastian Failing"
  info = "Systemintegrator"
  description = "Sebastian Failing's persoenliche website"
  keywords = "blog,sysadmin,Leipzig IT,IT,Netzwerke,Systemintegration"
  
  # Achte auf exakte Groß/Kleinschreibung der Datei im Ordner static/images/
  featured_image = "images/Me.JPG" 
  
  # Ananke nutzt oft dieses Format für zusätzliches CSS
  custom_css = ["css/custom.css"]

 

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Keekerino/Keekerino"


# Menu links

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/posts/"  # muss im absoluten pfad angegeben werden

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"    # muss im absoluten pfad angegeben werden