baseurl = "Meine.Domain.de"
title = "Keeks IT-Blog"
theme = "ananke"
languagecode = "de"
defaultcontentlanguage = "de"
locale = 'de-DE'


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
style = "github-dark"

[params]
  author = "Sebastian Failing"
  info = "Systemintegrator"
  description = "Sebastian Failing's persoenliche website"
  keywords = "blog,sysadmin,Leipzig IT,IT,Netzwerke,Systemintegration"
  avatarurl = ""
  #gravatar = ""

  faviconSVG = ""
  favicon_32 = ""
  favicon_16 = ""

  since = 2026

  enableEmoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Keekerino/Keekerino"



# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"