# ==========================================
# BASIS EINSTELLUNGEN
# ==========================================
baseURL = "https://keeks-it-blog.de/"
title = "Keeks IT-Blog"
theme = "ananke"
languageCode = "de-de"
defaultContentLanguage = 'de'
since = 2026
relativeURLs = true
canonifyURLs = true

# SEO & Funktionen (Muss auf der Root-Ebene stehen)
enableRobotsTXT = true
enableEmoji = true

# Design / Dark Mode (Ananke/Theme spezifisch)
colorScheme = "auto"
hidecolorschemetoggle = false

# ==========================================
# INHALTS-STEUERUNG (MARKUP & PAGINATION)
# ==========================================
[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  # Erlaubt HTML in Markdown 
  unsafe = true

[markup.highlight]
  # Code-Highlighting Style
  style = "github-dark"

# ==========================================
# TAXONOMIEN (SORTIERUNG)
# ==========================================
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# ==========================================
# EXTERNE DIENSTE
# ==========================================
[services.disqus]
  shortname = "Seb"

# ==========================================
# THEME PARAMETER (ANANKE SPEZIFISCH)
# ==========================================
[params]
  author = "Keeks"
  info = "Systemintegrator"
  description = "Keeks's persönliche Webseite über Systemintegration & Netzwerke"
  keywords = "blog, sysadmin, Leipzig IT, IT, Netzwerke, Systemintegration"
  
  # Datumsformat für die Anzeige (Deutsch)
  date_format = "02.01.2006"
  
  # Legt fest, welche Sektion auf der Startseite erscheint
  mainSections = ["posts"]
  
  # Globales Beitragsbild (Standard leer)
  featured_image = "" 
  
  # Eigene Styles & Scripte
  custom_css = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

# ==========================================
# SOCIAL LINKS
# ==========================================
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Keekerino/Keekerino"

# ==========================================
# HAUPTMENÜ (NAVIGATION)
# ==========================================
[[menu.main]]
  name = "Blog"
  weight = 1
  url = "/posts/"

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"


# ==========================================
# Related LINKS
# ==========================================

  [related]
  includeNewer = true
  threshold = 0
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10
